require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - db/**/**
    - features/support/env.rb
    - config/**/**
    - test/**/**
    - bin/**/**
    - node_modules/**/**
Layout/LineLength:
  Max: 120
Metrics/ClassLength:
  Max: 200
Metrics/BlockLength:
  Max: 80
Metrics/MethodLength:
  Enabled: false
Style/BlockComments:
  Enabled: false
Style/HashLikeCase:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/GuardClause:
  Enabled: false
RSpec/MultipleExpectations:
  Exclude:
    - spec/system/**
    - spec/system/admin/payment_status_spec.rb
    - spec/requests/**/**
Metrics/AbcSize:
  Exclude:
    - app/controllers/**
    - app/services/**/**
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Max: 10
